[server]
port = 80
debug = false

[database]
host = "localhost"
port = 5432
user = "postgres"
password = "password"
db = "echo-boilerplate"
ssl_mode = "disable"  # "disable", "allow", "prefer", "require"

[security]
allowed_hosts = []
hsts_max_age = 3600
xss_protection = "1; mode=block"
content_type_nosniff = "nosniff"
x_frame_options = "SAMEORIGIN"
referrer_policy = "strict-origin"
csp_default_src = "'self'"
csp_script_src = "'self'"
csp_style_src = "'self'"
csp_img_src = "'self'"
csp_font_src = "'self'"

[session]
key = "13d45bf0a822b832cc8886fa41ce4ced30584189bad02ec8ce552ace0d1ae8b1"  # hex encoded 32 byte string
enc_key = "2bb61a68ac3dec4f7c25efb062f4ae3b"  # hex encoded 16 byte string
path = "/"
domain = ""
max_age = 2592000
secure = false
http_only = true
same_site = 2  # Default = 1, Lax = 2, Strict = 3, None = 4
